version: '3'

services:

  traefik:
    image: traefik:v2.6
    command: 
      - "--api.insecure=true"           # The Web UI
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"                     # The Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  srv1:
    image: traefik/whoami
    hostname: srv1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http_srv1.rule=Host(`srv1.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.http_srv1.entrypoints=web"

  srv2:
    image: traefik/whoami
    hostname: srv2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http_srv2.rule=Host(`srv2.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.http_srv2.entrypoints=web"

  srv3:
    image: traefik/whoami
    hostname: srv3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http_srv3.rule=Host(`srv3.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.http_srv3.entrypoints=web"